version: '3.8'

services:
  postgres:
    image: postgres:14.11
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: halo-suster
    ports: 
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: 
      unless-stopped

volumes:
  postgres_data:
    driver: local
