Environment: development
LogLevel: debug
AUTHEXPIRY: 1 # in hours

DB:
  Name: db_halo_suster_be
  Port: 5432
  Host: localhost
  Username: postgres
  Password: rahasia
  Params: sslmode=disable
  MaxIdleConns: 20
  MaxOpenConns: 20

Jwt:
  Secret: mysecret
  BcryptSalt: 10

S3:
  ID: myid
  SecretKey: mysecret
  BucketName: mybucket
  Region: us-east-1